### ISSUE TITLE
How to pass query string parameters?

### ISSUE THREAD

**Issue by ZackStone** [molovo/consumer#3]
e.g. [jsonplaceholder.typicode.com / comments **? postId = 1**](https://jsonplaceholder.typicode.com/comments?postId=1)

**Comment by molovo** [comment]
This is technically possible, but not in the most intuitive way.

In theory, this should work:

```js
const api = consume('https://jsonplaceholder.typicode.com')
const comments = await api['comments?postId=1'].all()
```

I do plan on building a more intuitive API for this fairly soon though (something like `.where()`), as it's something I need myself.

**Comment by ZackStone** [comment]
Nice! Thanks.
